# Generated by Django 6.1.1 on 2026-09-19 16:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'ordering': ['id'], 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['-fecha_matricula', 'id'], 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['-fecha_inicio'], 'verbose_name_plural': 'Periodos'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='calificaciones.evaluacion'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='calificaciones.materia'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='calificaciones.periodo'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='materia',
            name='creditos',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='calificaciones.curso'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='calificaciones.periodo'),
        ),
    ]
